### ISSUE TITLE
Rename destination db

### ISSUE THREAD

**Issue by jaredmdobson** [bakwc/mysql_ch_replicator#90]
Hey there, thank you so much for making this!

Is there any way to rename the destination db on clickhouse to something different then the source db?

Also UUID's in MySQL seem to be mapped to Strings in Clickhouse?  Anyway to map them to UUIDs?

**Comment by bakwc** [comment]
Fixed in [v0.0.64](https://github.com/bakwc/mysql_ch_replicator/releases/tag/v0.0.64)

For rename added a `target_databases` config option, example:

```
target_databases:
  source_db_in_mysql_1: destination_db_in_clickhouse_1
  source_db_in_mysql_2: destination_db_in_clickhouse_2
  ...
```

For UUID - also added support for it. As there is no dedicated type in MySQL but rather char(36) or binary(16) - you need to set additional config option, eg:

```
types_mapping:
  'char(36)': 'UUID'
```
It will make convert char(36) in MySQL to UUID in ClickHouse

Please update and check if it works for you.
